### ISSUE TITLE
Could you please explain the equation 1 in your technical report?

### ISSUE THREAD

**Issue by sonack** [kedartatwawadi/NN_compression#10]
![image](https://user-images.githubusercontent.com/12935189/42746389-2de5f59c-890a-11e8-8612-47340e278827.png)

Why there is an addition with 2/N ?

**Comment by kedartatwawadi** [comment]
The 2/N is due to bounds on the performance of arithmetic coding. More information is in the cited reference (Cover, Thomas Elements of Information Theory'. 

You can also take a look here (section 6.2) https://web.archive.org/web/20070630050721/http://www.inference.phy.cam.ac.uk/itprnn/book.pdf
