### ISSUE TITLE
Will the project support more input characters

### ISSUE THREAD

**Issue by yyao9** [kedartatwawadi/NN_compression#5]
I try to run the sample, and find out it seems currently the tool could support limited input characters, like string containing only 'a' and 'b', will the tool support all 256 characters given the minimum input unit is 1 byte, thanks.

**Comment by kedartatwawadi** [comment]
Currently the interface is very crude. You can add whatever characters (say a-z) in the vocab list:
(line 34, of char_rnn.py) using the command option --vocab. 

`parser.add_argument('--vocab', type=str, default="ab")`

**Comment by kedartatwawadi** [comment]
Will improve the interface to detect the vocab from the input text
