### ISSUE TITLE
what's the meaning of k of markov-k

### ISSUE THREAD

**Issue by viviancui59** [kedartatwawadi/NN_compression#7]

**Comment by viviancui59** [comment]
we all know markov chain means that the final state just connect to its previous state. So I don't know the meaning of the ‘k’. I see it in the generate_sequence.py and run.py.

**Comment by viviancui59** [comment]
I guess it may means the length of sequence, but I don't know why it appears in generating sequence.

**Comment by viviancui59** [comment]
Oh,maybe I found this answer already.HMM=Hidden markov model

**Comment by suikammd** [comment]
Does it mean the current state relates to the first and the 20th state before it?
